### ISSUE TITLE
Your bundle is locked to rake (11.3.0)

### ISSUE THREAD

**Issue by bgvo** [ruby/rake#172]
For some reason, after doing `bundle update` this error comes out:

I checked Rubygems and the release is there (11.3.0). Any ideas how can I solve this? Thank you!

```
/var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:179:in `rescue in specs': Your bundle is locked to rake (11.3.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of rake (11.3.0) has removed it. You'll need to update your bundle to a different version of rake (11.3.0) that hasn't been removed in order to install. (Bundler::GemNotFound)
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:173:in `specs'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:233:in `specs_for'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:222:in `requested_specs'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/runtime.rb:118:in `block in definition_method'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/runtime.rb:19:in `setup'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler.rb:99:in `setup'
	from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by hsbt** [comment]
It's bundler specification. not rake issue.

**Comment by RogerRussel** [comment]
@bgvo as @hsbt said perheps it is not a problema with rake.
anyway you should try it on stacker overflow instead. 

http://stackoverflow.com/questions/40022328/gemnotfound-rake-when-using-whenever-in-development
For my, this problem solve the same issue that you had, on my project.

gem regenerate_binstubs

best regards.
