### ISSUE TITLE
Rake gives LoadError

### ISSUE THREAD

**Issue by AlcalaO** [ruby/rake#206]
I'm doing The odin project, and in the mini-project about ruby programming and rspec i need to do rake to the test but every time i write rake in the exercise folder it gives me this LoadError: 

```
`▶ rake
(in /home/odar/Documents/Practicas  TOP/TOP/learn_ruby)

An error occurred while loading ./TOP/TOP/learn_ruby/01_temperature.
Failure/Error: load file

LoadError:
  cannot load such file -- /home/odar/Documents/Practicas  TOP/TOP/learn_ruby/TOP/TOP/learn_ruby/01_temperature
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load_spec_file_handling_errors'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1494:in `block in load_spec_files'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `each'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `load_spec_files'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:100:in `setup'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/exe/rspec:4:in `<main>'
# 
#   Showing full backtrace because every line was filtered out.
#   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
#   RSpec::Configuration#backtrace_inclusion_patterns for more information.

An error occurred while loading ./TOP/TOP/learn_ruby/01_temperature/solution.
Failure/Error: load file

LoadError:
  cannot load such file -- /home/odar/Documents/Practicas  TOP/TOP/learn_ruby/TOP/TOP/learn_ruby/01_temperature/solution
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load_spec_file_handling_errors'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1494:in `block in load_spec_files'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `each'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `load_spec_files'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:100:in `setup'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
# /home/odar/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.6.0/exe/rspec:4:in `<main>'
# 
#   Showing full backtrace because every line was filtered out.
#   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
#   RSpec::Configuration#backtrace_inclusion_patterns for more information.

An error occurred while loading ./01_temperature/temperature_spec.rb.
Failure/Error: require "temperature"

LoadError:
  cannot load such file -- temperature
# ./01_temperature/temperature_spec.rb:18:in `require'
# ./01_temperature/temperature_spec.rb:18:in `<top (required)>'
No examples found.

Finished in 0.00028 seconds (files took 0.28103 seconds to load)
0 examples, 0 failures, 3 errors occurred outside of examples`
```

I've reinstalling everythig 2 times and i can't get it works

**Comment by drbrain** [comment]
This LoadError does not come from rake, you will need to contact the odin project for support for their rakefiles.
