### ISSUE TITLE
rake 10.4.2 doesn't support "rake -f <filename>"

### ISSUE THREAD

**Issue by BMayneFactual** [ruby/rake#23]
```
ben-dev-d4a ~/code $ rake --version
rake, version 10.4.2
ben-dev-d4a ~/code $ rake -f scarecrow-rules/scripts/crow/Rakefile
/home/benmayne/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/test/unit.rb:49:in `process_args': invalid option: -f (OptionParser::InvalidOption)
        from /home/benmayne/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/minitest/unit.rb:891:in `_run'
        from /home/benmayne/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/minitest/unit.rb:884:in `run'
        from /home/benmayne/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/test/unit.rb:21:in `run'
        from /home/benmayne/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/test/unit.rb:326:in `block (2 levels) in autorun'
        from /home/benmayne/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/test/unit.rb:27:in `run_once'
        from /home/benmayne/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/test/unit.rb:325:in `block in autorun'
ben-dev-d4a ~/code $
```

Downgrading to 10.3.2 solves the problem. `--rakefile` has the same problem.

**Comment by hsbt** [comment]
I can't reproduce this. If you still have this issue, Please reopen this. (and try with Ruby 2.1 or 2.2)
