### ISSUE TITLE
Rake 10.4.2 segfaults on ruby 2.2.3

### ISSUE THREAD

**Issue by mikz** [ruby/rake#65]
Here is minimal reproducible case:

`task.rake`
```ruby
require 'rake/tasklib'

class CapistranoTask < ::Rake::TaskLib
  def initialize
    namespace(:unicorn, &method(:define))
  end

  def define(*)
    namespace :config do

    end
  end
end

CapistranoTask.new
```

in Rakefile
```ruby
Rake.application.add_import('./task.rake')
```

and just run `rake whatever`.

It segfaults with:

```
ruby-2.2.3/lib/ruby/2.2.0/rake/task_manager.rb:210: [BUG] Stack consistency error (sp: 65, bp: 64)
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

-- Control frame information -----------------------------------------------
c:0018 p:0081 s:0065 e:000063 METHOD /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task_manager.rb:210
c:0017 p:0095 s:0059 e:000058 METHOD /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/dsl_definition.rb:147
c:0016 p:0014 s:0054 e:000053 METHOD /Users/mikz/Developer/3scale/deploy/test/1c47d36b083961e1291b/unicorn.rake:5 [FINISH]
c:0015 p:---- s:0051 e:000050 CFUNC  :new
c:0014 p:0040 s:0048 e:000047 TOP    /Users/mikz/Developer/3scale/deploy/test/1c47d36b083961e1291b/unicorn.rake:15 [FINISH]
c:0013 p:---- s:0046 e:000045 CFUNC  :load
c:0012 p:0009 s:0042 e:000041 METHOD /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28
c:0011 p:0024 s:0038 e:000037 METHOD /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/default_loader.rb:10
c:0010 p:0084 s:0034 e:000033 METHOD /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:767
c:0009 p:0192 s:0027 E:0001a0 METHOD /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:697
c:0008 p:0007 s:0022 e:000021 BLOCK  /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:94
c:0007 p:0006 s:0020 e:000019 METHOD /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176
c:0006 p:0007 s:0016 e:000015 METHOD /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:93
c:0005 p:0013 s:0013 e:000012 BLOCK  /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:77
c:0004 p:0006 s:0011 e:000010 METHOD /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176
c:0003 p:0007 s:0007 e:000006 METHOD /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75
c:0002 p:0040 s:0004 E:001ab0 EVAL   /Users/mikz/.rvm/rubies/ruby-2.2.3/bin/rake:37 [FINISH]
c:0001 p:0000 s:0002 E:0006e0 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/mikz/.rvm/rubies/ruby-2.2.3/bin/rake:37:in `<main>'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:697:in `raw_load_rakefile'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:767:in `load_imports'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/default_loader.rb:10:in `load'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/Users/mikz/Developer/3scale/deploy/test/1c47d36b083961e1291b/unicorn.rake:15:in `<top (required)>'
/Users/mikz/Developer/3scale/deploy/test/1c47d36b083961e1291b/unicorn.rake:15:in `new'
/Users/mikz/Developer/3scale/deploy/test/1c47d36b083961e1291b/unicorn.rake:5:in `initialize'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/dsl_definition.rb:147:in `namespace'
/Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task_manager.rb:210:in `in_namespace'

-- C level backtrace information -------------------------------------------
0   ruby                                0x0000000103a6fb65 rb_vm_bugreport + 149
1   ruby                                0x0000000103912524 rb_bug + 468
2   ruby                                0x0000000103a51fc3 vm_exec_core + 17427
3   ruby                                0x0000000103a60941 vm_exec + 129
4   ruby                                0x0000000103a69382 rb_call0 + 674
5   ruby                                0x000000010397a159 rb_class_new_instance + 41
6   ruby                                0x0000000103a6da85 vm_call_cfunc + 1797
7   ruby                                0x0000000103a6cb4f vm_call_method + 895
8   ruby                                0x0000000103a51240 vm_exec_core + 13968
9   ruby                                0x0000000103a60941 vm_exec + 129
10  ruby                                0x0000000103a6088d rb_iseq_eval + 285
11  ruby                                0x00000001039208eb rb_load_internal0 + 315
12  ruby                                0x000000010392059a rb_f_load + 186
13  ruby                                0x0000000103a6da85 vm_call_cfunc + 1797
14  ruby                                0x0000000103a51240 vm_exec_core + 13968
15  ruby                                0x0000000103a60941 vm_exec + 129
16  ruby                                0x0000000103a61518 rb_iseq_eval_main + 504
17  ruby                                0x000000010391b534 ruby_exec_internal + 148
18  ruby                                0x000000010391b45e ruby_run_node + 78
19  ruby                                0x00000001037c727f main + 79

-- Other runtime information -----------------------------------------------

* Loaded script: /Users/mikz/.rvm/rubies/ruby-2.2.3/bin/rake

* Loaded features:

    0 enumerator.so
    1 rational.so
    2 complex.so
    3 encdb.so
    4 trans/transdb.so
    5 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/unicode_normalize.rb
    6 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/x86_64-darwin14/rbconfig.rb
    7 thread.rb
    8 thread.so
    9 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/compatibility.rb
   10 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/defaults.rb
   11 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/deprecate.rb
   12 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/errors.rb
   13 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/version.rb
   14 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/requirement.rb
   15 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/platform.rb
   16 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/basic_specification.rb
   17 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/stub_specification.rb
   18 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/util/stringio.rb
   19 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb
   20 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/exceptions.rb
   21 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb
   22 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb
   23 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb
   24 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems.rb
   25 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb
   26 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/path_support.rb
   27 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/version.rb
   28 etc.so
   29 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb
   30 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/singleton.rb
   31 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/optparse.rb
   32 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/ostruct.rb
   33 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/ext/module.rb
   34 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/ext/core.rb
   35 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/ext/string.rb
   36 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/early_time.rb
   37 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/late_time.rb
   38 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/ext/time.rb
   39 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/alt_system.rb
   40 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/win32.rb
   41 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/linked_list.rb
   42 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/cpu_counter.rb
   43 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/scope.rb
   44 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task_argument_error.rb
   45 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rule_recursion_overflow_error.rb
   46 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/shellwords.rb
   47 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task_manager.rb
   48 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/cloneable.rb
   49 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_utils.rb
   50 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_utils_ext.rb
   51 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/pathmap.rb
   52 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_list.rb
   53 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb
   54 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/promise.rb
   55 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/thread_pool.rb
   56 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/private_reader.rb
   57 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/thread_history_display.rb
   58 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/trace_output.rb
   59 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb
   60 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_module.rb
   61 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/pseudo_status.rb
   62 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task_arguments.rb
   63 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/invocation_chain.rb
   64 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/invocation_exception_mixin.rb
   65 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb
   66 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_task.rb
   67 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_creation_task.rb
   68 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/multi_task.rb
   69 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/dsl_definition.rb
   70 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/default_loader.rb
   71 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/name_space.rb
   72 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/backtrace.rb
   73 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake.rb
   74 /Users/mikz/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/tasklib.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html
```

It segfaults the same way on Linux machine with Ruby 2.2.2.

Will report it to Ruby also.

**Comment by mikz** [comment]
Looks like proper Ruby bug. https://bugs.ruby-lang.org/issues/11451
